server:
  port: 8080

proxy-target:
  base-url: "http://192.168.194.250:8080/api"

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: proxy-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      eventos: eventos

  redis:
    host: 192.168.194.250
    port: 6379
app:
  jwt:
    base64-secret:NzdiYWQ4OTIyYjEzMDUyYzhiNmVhNDk4MzViNzdkYjBiZjEwMmJjZDI2ZGNlNWYxY2JiOTI4YjEyYjJjNjcyYzEzOWFmYTRiNjc3MzA5OWUxMDUxY2FiZjBmNmI1ODgzZjFlZWU4N2Y5MTI4NzMzMmEyN2QzYmU4OTQ0NTJjNDU=
